version: '3.9'

services:
  db:
    image: postgres:16
    container_name: roomraid_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: roomraid_web
    command: >
      sh -c "
        python manage.py migrate &&
        echo \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@admin.com', 'admin')\" | python manage.py shell &&
        echo \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='usuario').exists() or User.objects.create_user('usuario', 'usuario@usuario.com', 'usuario')\" | python manage.py shell &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data: