# Generated by Django 6.0.2 on 2026-02-20 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('capacidad', models.PositiveIntegerField(verbose_name='Capacidad')),
                ('ubicacion', models.CharField(max_length=150, verbose_name='Ubicacion')),
                ('recursos', models.CharField(choices=[('proyector', 'Proyector'), ('pizarra', 'Pizarra'), ('tv', 'Televisión'), ('hdmi', 'HDMI'), ('aire_acondi', 'Aire acondicionado')], max_length=50, verbose_name='Recursos')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Espacio',
                'verbose_name_plural': 'Espacios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
                ('condiciones', models.TextField(blank=True, max_length=500, null=True, verbose_name='Condiciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('espacios', models.ManyToManyField(related_name='tarifas', related_query_name='tarifa', to='bookings.space', verbose_name='Espacios')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Franja Horaria',
                'verbose_name_plural': 'Franjas Horarias',
                'ordering': ['hora_inicio'],
                'unique_together': {('hora_inicio', 'hora_fin')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, max_length=500, null=True, verbose_name='Notas')),
                ('coste_total', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Coste total')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', related_query_name='reserva', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('tarifa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', related_query_name='reserva', to='bookings.rate', verbose_name='Tarifa')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', related_query_name='reserva', to='bookings.space', verbose_name='Espacio')),
                ('franjas', models.ManyToManyField(related_name='reservas', related_query_name='reserva', to='bookings.timeslot', verbose_name='Franjas horarias')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['fecha', 'espacio'],
            },
        ),
    ]
