# Generated by Django 6.0.2 on 2026-02-19 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('capacidad', models.PositiveIntegerField(verbose_name='Capacidad')),
                ('ubicacion', models.CharField(max_length=150, verbose_name='Ubicacion')),
                ('recursos', models.CharField(choices=[('proyector', 'Proyector'), ('pizarra', 'Pizarra'), ('tv', 'Televisión'), ('hdmi', 'HDMI'), ('aire_acondi', 'Aire acondicionado')], max_length=50, verbose_name='Recursos')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Espacio',
                'verbose_name_plural': 'Espacios',
                'ordering': ['nombre'],
            },
        ),
    ]
