# Generated by Django 6.0.2 on 2026-02-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='contador_reservas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
