# Generated by Django 6.0.2 on 2026-02-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre_Tarifa')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
                ('condiciones', models.TextField(blank=True, null=True, verbose_name='Condiciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('espacios', models.ManyToManyField(related_name='tarifas', related_query_name='tarifa', to='bookings.space', verbose_name='Espacios')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Franja Horaria',
                'verbose_name_plural': 'Franjas Horarias',
                'ordering': ['hora_inicio'],
                'unique_together': {('hora_inicio', 'hora_fin')},
            },
        ),
    ]
