# Generated by Django 6.0.2 on 2026-02-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rate_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='condiciones',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Condiciones'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
    ]
