# Generated by Django 6.0.2 on 2026-02-19 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_rate_condiciones_alter_rate_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, max_length=500, null=True, verbose_name='Notas')),
                ('coste_total', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Coste total')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', related_query_name='reserva', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', related_query_name='reserva', to='bookings.space', verbose_name='Espacio')),
                ('franjas', models.ManyToManyField(related_name='reservas', related_query_name='reserva', to='bookings.timeslot', verbose_name='Franjas horarias')),
                ('tarifa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', related_query_name='reserva', to='bookings.rate', verbose_name='Tarifa')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['fecha', 'espacio'],
            },
        ),
    ]
